#pragma once

template <class T>
class CProxy_IModEvents : public IConnectionPointImpl<T, &__uuidof(_IModEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
