#pragma once

template <class T>
class CProxy_ICalculatorEvents : public IConnectionPointImpl<T, &__uuidof(_ICalculatorEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
